# Read the documentation: https://symfony.com/doc/current/bundles/FOSCKEditorBundle/index.html

fos_ck_editor:
    autoload: false
    input_sync: false
    
    configs:
        my_config:
            toolbar: full
            language: en
            uiColor: '#f7f7f7'
            height: 300
            startupFocus: false
            removeButtons: 'Save,NewPage,Preview,Print,Templates'
            autoGrow_minHeight: 200
            autoGrow_maxHeight: 400
            disableAutoInline: true